export const BASE_KEYWORDS = [
    "Fakhri IT Services", "Fakhri Pinnacle Consulting", "Fakhri IT", "FakhriIT", "FakhriITS",
    "Amazon SPN Partner", "Amazon Service Provider India", "Amazon Account Management Services",
    "Amazon PPC Management Indore", "Amazon Advertising Agency India", "Amazon SEO Indore",
    "Amazon Listing Optimization", "Amazon EBC Content", "Amazon A+ Content Design",
    "Amazon Brand Registry Services India", "Amazon Seller Central Support", "FBA Management Services",
    "Amazon Global Selling India", "Amazon Training Indore", "Amazon Specialist India",
    "Amazon Growth Partner", "Increase Amazon Sales India", "Reduce Amazon ACoS India",
    "Amazon Suspension Appeal India", "Amazon Reinstatement Services", "Amazon Product Launch Strategy",
    "Amazon Cataloging Services India", "Amazon Product Photography India", "Amazon Graphic Design Services",
    "Fakri IT Services Indore", "Phakhri IT Services India", "Fakhry IT Services", "Fakhri IT Solution",
    "Amazon Seller Services Indore", "Amazon Consulting Indore", "Amazon Marketing Indore",
    "Fakhri IT Consulting", "Pinnacle Consulting Indore", "Amazon IT Services India",
    "Amazon Marketplace Services India", "E-commerce Management India", "Online Business Growth India",
    "Amazon Store Setup India", "Amazon PPC Services indore", "Amazon Advertising india",
    "Fakhri IT Services Reviews", "Fakhri IT Services Contact", "Fakhri IT Services Office",
    "Amazon SPN India List", "Amazon Service Provider Network India", "Amazon Seller Indore Help",
    "Amazon Virtual Assistant India", "Amazon Store Manager India", "Amazon SPN Indore",
    "Amazon Private Label Expert India", "Amazon Wholesale FBA India", "Amazon Dropshipping India",
    "Amazon Account Reactivation India", "Amazon Trademark Registration India",
    "Flipkart Seller Services India", "Meesho Account Management India", "Ebay Global Selling India",
    "Shopify Expert India", "Digital Marketing Agency Indore", "Social Media Marketing Indore",
    "Website Development Indore", "Search Engine Optimization Indore", "Meta Ads Management India",
    "Google Ads Management Indore", "E-commerce SEO India", "Brand Building India",
    "Fakree IT Services", "Fakhari IT Services", "Phakhree IT Services", "Fakhri Solutions Indore",
    "Amazon SPN Delhi", "Amazon SPN Mumbai", "Amazon SPN Bangalore", "Amazon SPN Hyderabad",
    "Amazon SPN Chennai", "Amazon SPN Kolkata", "Amazon SPN Ahmedabad", "Amazon SPN Pune",
    "Amazon SPN Surat", "Amazon SPN Jaipur", "Amazon SPN Lucknow", "Amazon SPN Kanpur",
    "Amazon SPN Nagpur", "Amazon SPN Visakhapatnam", "Amazon SPN Indore Office",
    "Amazon Seller Support Contact India", "Amazon Account Manager Fees India",
    "Hire Amazon Expert India", "Best Amazon Agency India", "Top Amazon Consulting India",
    "Amazon Sales Growth Secrets", "Amazon Advertising Indore Services", "Amazon PPC Experts India",
    "Amazon Listing Services Indore", "Amazon Content Indore", "Amazon Design Indore",
    "Amazon Fakhri IT", "Fakhri IT Services Location", "Fakhri IT Services Website",
    "Amazon Seller Services Near Me", "Amazon Account Management Near Me", "Amazon PPC Near Me",
    "Amazon SEO Near Me", "Amazon Listing Near Me", "Amazon Design Near Me", "Amazon Help India",
    "Amazon Brand Management India", "Amazon Product Hunting India", "Amazon Keywords Research India",
    "Amazon Competitor Analysis India", "Amazon Coupon Management India", "Amazon Lightning Deals India",
    "Amazon Advertising Optimization India", "Amazon FBA Shipment Support India",
    "Amazon Inventory Management India", "Amazon Returns Management India", "Amazon Feedback Management India",
    "Amazon Review Management India", "Amazon Seller Performance India", "Amazon Account Audit India",
    "Amazon Strategy Consulting India", "Amazon Business Solutions India", "Amazon Enterprise Support India",
    "Amazon Small Business Support India", "Amazon Seller Central India Help", "Amazon Seller App India Help",
    "Fakhri IT Digital", "Fakhri IT Business", "Fakhri IT Growth", "Fakhri IT Partner",
    "Amazon SPN Partner Indore MP", "Amazon SPN Madhya Pradesh", "Amazon SPN Central India",
    "Indore Amazon Service Provider", "MP Amazon Seller Services", "Central India Amazon Consulting",
    "Amazon Seller Coaching Indore", "Amazon Workshop Indore", "Amazon Seminar India",
    "Amazon E-commerce Agency India", "Full Service Amazon Agency India", "PPC Management Agency India",
    "SEO Agency Indore", "Marketing Agency MP", "Advertising Agency Central India",
    "Ecommerce Growth Partner India", "Scaling Amazon Brands India", "Amazon Aggregator India Partner",
    "Amazon Seller Exit Strategy India", "Selling Amazon Business India", "Buying Amazon Business India",
    "Amazon Investment Advice India", "Amazon Profitability Consulting India",
    "Amazon Ads Strategy 2024", "Amazon Ads Strategy 2025", "Amazon Future Planning India",
    "Amazon Global Expansion India", "Amazon US Marketplace Help India", "Amazon UK Marketplace Help India",
    "Amazon UAE Marketplace Help India", "Amazon Germany Marketplace Help India",
    "Amazon Canada Marketplace Help India", "Amazon Australia Marketplace Help India",
    "Amazon Japan Marketplace Help India", "Amazon Singapore Marketplace Help India",
    "Amazon Mexico Marketplace Help India", "Amazon Brazil Marketplace Help India",
    "Amazon France Marketplace Help India", "Amazon Italy Marketplace Help India",
    "Amazon Spain Marketplace Help India", "Amazon Netherlands Marketplace Help India",
    "Amazon Poland Marketplace Help India", "Amazon Sweden Marketplace Help India",
    "Amazon Turkey Marketplace Help India", "Amazon Saudi Arabia Marketplace Help India",
    "Amazon Egypt Marketplace Help India", "Amazon South Africa Marketplace Help India",
    "Amazon SPN USA", "Amazon SPN UK", "Amazon SPN UAE", "Amazon SPN Australia",
    "Amazon Account Scaling Experts", "Ecommerce Automation India", "Amazon Bot Protection Help",
    "Amazon Buy Box Optimization", "Amazon PPC Audit Free India", "Amazon Seller Audit Services",
    "Amazon Account Manager Indore", "Amazon Business Coach India", "Amazon Sales Expert Indore",
    "How to increase Amazon sales India", "Best Amazon SPN in Indore", "Fakhri IT Services Office Address",
    "Fakhri IT Contact Number", "Amazon Seller Support India Toll Free", "Amazon SPN Fees in India",
    "Amazon Cataloging fees India", "Amazon A+ content cost India", "Amazon Imaging services Indore",
    "Amazon Product Video Production India", "Amazon Brand Story Design India",
    "Amazon Store Design Expert India", "Amazon Marketplace Growth Agency",
    "Amazon Account Management Agency India", "Amazon Advertising Management India",
    "Amazon Marketing Services India", "Amazon Web Services Seller Support",
    "Amazon Cloud Seller Support", "Amazon Data Analytics for Sellers India",
    "Amazon Sales Reporting Services", "Amazon Reconciliation Services India",
    "Amazon Reimbursement Services India", "Amazon Safe-T claim help India",
    "Amazon Intellectual Property support India", "Amazon Counterfeit removal India",
    "Amazon Brand Protection India", "Amazon Transparency Program help India",
    "Amazon Project Zero support India", "Amazon Vine Program management India",
    "Amazon Early Reviewer Program alternatives", "Amazon Custom products setup India",
    "Amazon Handmade seller support India", "Amazon Launchpad management India",
    "Amazon Business B2B setup India", "Amazon Global Selling USA from India",
    "Amazon Export support India", "Amazon Logistics support India",
    "Amazon Easy Ship support Indore", "Amazon Self Ship support India",
    "Amazon Flex seller support India", "Amazon Seller Flex Indore",
    "Amazon Warehouse management India", "Amazon FBA prep services India",
    "Amazon Labeling services India", "Amazon Removal order help India",
    "Amazon Disposal order help India", "Amazon Account Health management India",
    "Amazon ODR improvement services", "Amazon VTR improvement help",
    "Amazon LDR reduction services", "Amazon Customer service for sellers India",
    "Amazon Buyer Seller messaging help", "Amazon Feedback removal services India",
    "Amazon Listing suppression fix", "Amazon Restricted products appeal India",
    "Amazon Category ungating services India", "Amazon Brand ungating services India",
    "Amazon ASIN reinstatement India", "Amazon Search terms optimization",
    "Amazon Browse nodes optimization India", "Amazon Title optimization services",
    "Amazon Bullet points optimization India", "Amazon Description optimization India",
    "Amazon Alt text for images India", "Amazon Keyword density for SEO",
    "Amazon Backend keywords optimization", "Amazon Platinum keywords help",
    "Amazon Target audience analysis India", "Amazon Niche research India",
    "Amazon Trend analysis India", "Amazon Seasonal sales strategy India",
    "Amazon Prime Day strategy India", "Amazon Great Indian Festival strategy",
    "Amazon Diwali sales strategy India", "Amazon Black Friday strategy India",
    "Amazon Cyber Monday strategy India", "Amazon New Year sales strategy India",
    "Amazon Christmas sales strategy India", "Amazon Holi sales strategy India",
    "Amazon Rakhi sales strategy India", "Amazon Valentine sales strategy India",
    "Amazon Mother's day sales strategy India", "Amazon Father's day sales strategy India",
    "fakhri", "fakhriitservices", "fakhri it services", "fakhri its", "fakhri it", "fakhripinnacle",
    "fakhri services", "fakhri india", "fakhri indore", "fakhri bhopal", "fakhri mp",
    "fakhri amazon", "fakhri flipkart", "fakhri meesho", "fakhri myntra", "fakhri jiomart",
    "fakhri amazon service", "fakhri account management", "fakhri ppc", "fakhri spn",

    "fakhri it services bhopal", "amazon service in bhopal", "amazon spn bhopal",
    "amazon account management bhopal", "amazon listing bhopal", "amazon seo bhopal",
    "ecommerce service bhopal", "flipkart service bhopal", "meesho service bhopal",
    "fakhari", "fakree", "fakhari it", "fakree it", "fakhre it", "fakhriitservice",
    "fakhriitservices.com", "www.fakhriitservices.com", "fakhri it services reviews",
    "fakhri it services salary", "fakhri it services address", "fakhri it services contact",
    "amazon fakhri", "flipkart fakhri", "meesho fakhri", "spn fakhri",
    "fakhry", "fakhry it", "fakhry it services", "phakhri", "phakhri it", "phakhri it services",
    "fakhri in bhopal", "fakhri in indore", "amazon service in mp", "amazon consultant bhopal",
    "amazon expert bhopal", "best amazon agency bhopal", "top amazon consultant mp",
    "fakhri it solutions", "fakhri it consulting", "fakhri pinnacle consulting bhopal",
    "pinnacle consulting amazon", "maurya fakhri", "fakhri kuldeep", "fakhri team",
    "fakhri offices", "fakhri support", "fakhri help", "fakhri consultancy", "fakhri", "fakhris", "fakhria", "fakhrib", "fakhric", "fakhrid", "fakhrie", "fakhrif", "fakhrig", "fakhrih", "fakhrii", "fakhrij", "fakhrik", "fakhril", "fakhrim", "fakhrin", "fakhrio", "fakhrip", "fakhriq", "fakhrir", "fakhris", "fakhrit", "fakhriu", "fakhriv", "fakhriw", "fakhrix", "fakhriy", "fakhriz", "fakhri it", "fakhri-it", "fakhriits", "itfakhri", "it fakhri", "fakhri itc", "fakhri itx", "fakhri itr", "fakhri itl", "fakhri itd", "fakhri ite", "fakhri itk", "fakhri itn", "fakhri itm", "fakhri its", "fakhri itg", "fakhri ith", "fakhri itp", "fakhri itb", "fakhri itz"


];

export const SEO_CONFIG = {
    home: {
        title: "Fakhri IT Services | #1 Amazon SPN & Growth Partner India",
        description: "Scale your Amazon business with India's leading SPN partner. Expert account management, ROI-focused PPC, stunning A+ content, and strategic growth for global Amazon sellers. Based in Indore, serving worldwide.",
        keywords: [...BASE_KEYWORDS, "Amazon Success Indore", "Amazon Growth India", "Fakhri IT Home"]
    },
    about: {
        title: "About Us | The Journey of Fakhri IT Services",
        description: "Founded in 2016, Fakhri IT Services has empowered 500+ Amazon sellers globally. Learn about our mission, vision, and the expert team behind our award-winning Amazon consulting services.",
        keywords: [...BASE_KEYWORDS, "Fakhri IT Story", "About Fakhri IT", "Amazon Experts Team"]
    },
    services: {
        title: "Our Services | Amazon SPN Account Management & Advertising",
        description: "Explore our comprehensive suite of Amazon seller services: PPC management, listing optimization, EBC/A+ design, FBA operations, and account auditing. Your one-stop shop for Amazon growth.",
        keywords: [...BASE_KEYWORDS, "Amazon PPC Indore", "Listing Optimization India", "Amazon A+ Content Indore"]
    },
    pricing: {
        title: "Pricing Plans | Affordable Amazon Management Packages",
        description: "Transparent and ROI-driven pricing for Amazon account management. Choose the plan that fits your business stage, from startup help to enterprise scaling.",
        keywords: [...BASE_KEYWORDS, "Amazon Management Fees India", "Amazon Service Packages", "Cheap Amazon Management"]
    },
    blog: {
        title: "Amazon Seller Blog | Latest Strategies & Market Updates",
        description: "Stay ahead of the curve with our Amazon seller blog. Expert tips on PPC, SEO, Amazon TOS updates, and case studies of successful global brands.",
        keywords: [...BASE_KEYWORDS, "Amazon Seller News India", "Amazon PPC Tips", "Amazon SEO Guide 2024"]
    },
    contact: {
        title: "Contact Us | Start Your Amazon Journey Today",
        description: "Get in touch with Fakhri IT Services Indore. Schedule a free consultation with our Amazon experts and discover how we can double your sales. Phone, Email, and WhatsApp support.",
        keywords: [...BASE_KEYWORDS, "Contact Fakhri IT", "Fakhri IT WhatsApp", "Fakhri IT Indore Office"]
    },
    career: {
        title: "Careers | Join the Elite Amazon Expert Team",
        description: "Want to build the future of Amazon brands? Join Fakhri IT Services. We're hiring account managers, PPC specialists, and content designers in Indore.",
        keywords: [...BASE_KEYWORDS, "Jobs in Indore", "Amazon Account Manager Jobs Indore", "Digital Marketing Careers Indore"]
    },
    policy: {
        title: "Policies | Privacy, Terms & Refund Information",
        description: "Read the official policies of Fakhri IT Services including our terms of service, privacy policy, and refund procedures.",
        keywords: [...BASE_KEYWORDS, "Fakhri IT Privacy Policy", "Fakhri IT Terms", "Refund Policy India"]
    }
};
