'use server';

import * as service from './services/content.service';

export const getServices = service.getServices;
export const getCatalogServices = service.getCatalogServices;
export const getFAQs = service.getFAQs;
export const getTeamMembers = service.getTeamMembers;
export const getTestimonials = service.getTestimonials;
export const getPricingPlans = service.getPricingPlans;
export const getCompanyData = service.getCompanyData;
export const getMilestones = service.getMilestones;
export const upsertMilestone = service.upsertMilestone;
export const deleteMilestone = service.deleteMilestone;
export const getJobs = service.getJobs;
export const updateCompanyData = service.updateCompanyData;
export const upsertTeamMember = service.upsertTeamMember;
export const deleteTeamMember = service.deleteTeamMember;
export const upsertPricingPlan = service.upsertPricingPlan;
export const deletePricingPlan = service.deletePricingPlan;
export const getPricingFeatures = service.getPricingFeatures;
export const upsertPricingFeature = service.upsertPricingFeature;
export const deletePricingFeature = service.deletePricingFeature;
export const upsertService = service.upsertService;
export const deleteService = service.deleteService;
export const upsertTestimonial = service.upsertTestimonial;
export const deleteTestimonial = service.deleteTestimonial;
export const upsertFAQ = service.upsertFAQ;
export const deleteFAQ = service.deleteFAQ;
export const upsertJob = service.upsertJob;
export const deleteJob = service.deleteJob;
export const upsertCatalogService = service.upsertCatalogService;
export const deleteCatalogService = service.deleteCatalogService;
export const getWebPage = service.getWebPage;
export const upsertWebPage = service.upsertWebPage;
export const getHSNs = service.getHSNs;
export const upsertHSN = service.upsertHSN;
export const deleteHSN = service.deleteHSN;
export const purgePublicCache = service.purgePublicCache;
